name: tex2typst Tests
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run Vitest Test
        run: npx vitest run
